# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32e835756dd782d563d09ce5d321479361f81d92f1a30bfa00de006d058863feb78cf5b49f1bfef5ee10ddb1d79d33b2ebf697e0a9b104bdbc02f351f67703fa

test:
  secret_key_base: b104705b847ef14be58f114580187b15b6df31d3031cea6a3a3282532e967684d7722bec9e09fd3823949625ae3cb6ea5766f7aaaab10bea77f6e79f64f8f172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
